resource_registry:
  OS::TripleO::Compute::Net::SoftwareConfig: /home/stack/templates/nic-configs/compute.yaml
  OS::TripleO::Controller::Net::SoftwareConfig: /home/stack/templates/nic-configs/controller.yaml
  OS::TripleO::CephStorage::Net::SoftwareConfig: /home/stack/templates/nic-configs/ceph-storage.yaml
  OS::TripleO::Remote::Net::SoftwareConfig: /home/stack/templates/nic-configs/remote.yaml

parameter_defaults:

  NeutronExternalNetworkBridge: "''"

  InternalApiNetworkVlanID: 18
  InternalApiNetCidr: 192.168.18.0/24
  InternalApiAllocationPools: [ { 'start': '192.168.18.101', 'end': '192.168.18.200' } ]
  InternalApiInterfaceDefaultRoute: 192.168.18.254

  InternalApi2NetworkVlanID: 18
  InternalApi2NetCidr: 192.168.118.0/24
  InternalApi2AllocationPools: [ { 'start': '192.168.118.101', 'end': '192.168.118.200' } ]
  InternalApi2InterfaceDefaultRoute: 192.168.118.254

  TenantNetworkVlanID: 20
  TenantNetCidr: 192.168.20.0/24
  TenantAllocationPools: [ { 'start': '192.168.20.101', 'end': '192.168.20.200' } ]
  TenantInterfaceDefaultRoute: 192.168.20.254

  Tenant2NetworkVlanID: 20
  Tenant2NetCidr: 192.168.120.0/24
  Tenant2AllocationPools: [ { 'start': '192.168.120.101', 'end': '192.168.120.200' } ]
  Tenant2InterfaceDefaultRoute: 192.168.120.254

  StorageNetworkVlanID: 248
  StorageNetCidr: 172.31.248.0/24
  StorageAllocationPools: [ { 'start': '172.31.248.101', 'end': '172.31.248.200' } ]

  StorageMgmtNetworkVlanID: 21
  StorageMgmtNetCidr: 192.168.21.0/24
  StorageMgmtAllocationPools: [ { 'start': '192.168.21.101', 'end': '192.168.21.200' } ]

  ExternalNetworkVlanID: 249
  ExternalNetCidr: 172.31.249.0/24
  ExternalInterfaceDefaultRoute: 172.31.249.254
  ExternalAllocationPools: [ { 'start': '172.31.249.101', 'end': '172.31.249.200' } ]

  ControlPlaneSubnetCidr: "24"
  ControlPlaneDefaultRoute: 192.168.19.254
  ControlPlaneNetCidr: 192.168.19.0/24
  EC2MetadataIp: 192.168.19.1
  DnsServers: [ '172.31.255.1' ]

  ControlPlane2SubnetCidr: "24"
  ControlPlane2DefaultRoute: 192.168.119.254
  ControlPlane2NetCidr: 192.168.119.0/24

  RemoteExtraConfig:
    neutron::agents::ml2::ovs::local_ip: "%{hiera('tenant2')}"
    nova::compute::libvirt::vncserver_listen: "%{hiera('internal_api2')}"
    nova::compute::vncserver_proxyclient_address: "%{hiera('internal_api2')}"
    cold_migration_ssh_inbound_addr: "%{hiera('internal_api2')}"
    live_migration_ssh_inbound_addr: "%{hiera('internal_api2')}"
    nova::migration::libvirt::live_migration_inbound_addr: "%{hiera('internal_api2')}"
    nova::my_ip: "%{hiera('internal_api2')}"
    tripleo::profile::base::database::mysql::client::mysql_client_bind_address: "%{hiera('internal_api2')}"
